# agent.py

from ..adapters.core.adapter import AgentAdapter
from ..tools.base.tool_base import Tool
from ..formatters.base_formatter import BaseFormatter
from ..formatters.formatter import Formatter
from ..adapters.core.adapter_classes import Message
from .agent_exceptions import MaxIterationsError
from .tool_executor import ToolExecutor
from ..memory.conversations import Conversation
from ..memory.core.memory import AgentMemory
from ..policy.agent_policy import AgentPolicy
from typing import Optional, List

import asyncio


class LilyAgent:
    """
    ### Definition
    - Base class for all Agents that is responsible for handling prompts and
    flow of interaction with a `LLM` (Large Language Model) Adapter.
    - It maintains conversational state, manages available **Tools** and **__Formatters__**,
    formats input and output responses for the model.

    ### Class Attributes
    - **tools**: `List[Tool]` => The list of tools available for an agent to perform actions/tool calls
    - **system_prompt**: `str` => Combination of agent role and prompt that defines the agent's behavior
    - **formatter**: `Formatter` => Responsible for formatting tool schema depending on the LLM.
    - **adapter**: `AgentAdapter` => Interface for communicating with the underlying LLM.
    - **messages**: `List[Message]` => Conversational history
    """

    def __init__(
            self, 
            adapter: AgentAdapter, 
            memory: Optional[AgentMemory] = None,
            tools: Optional[List[Tool]]=None, 
            formatter: Optional[Formatter] = None, 
            role: Optional[str] = None ,
            prompt: Optional[str] = None, 
            max_iter: int = 3,
            policy: Optional[AgentPolicy] = None,
    ) -> None:
        
        self.tools: List[Tool] = tools or []

        '''Default fallback role'''

        self.role = role if role is not None else "You are Lily, a helpful agent developed by Shree"
        '''Default fallback prompt'''

        self.prompt = prompt if prompt is not None else "Answer to user prompts and use tools whenever necessary."
        self.system_prompt: str = f"{self.role}\n\n{self.prompt}"
        self.max_iter: int = max_iter
        
        self.formatter = formatter if formatter is not None else BaseFormatter()
        self.adapter: AgentAdapter = adapter

        self.tool_executor: Optional[ToolExecutor] = ToolExecutor(tools=self.tools) if self.tools else None

        self.conversation: Conversation =  Conversation(self.system_prompt)

        self.memory: Optional[AgentMemory] = memory

        self.policy: Optional[AgentPolicy] = policy

        '''Private variables'''
        self._use_conversational_history: bool = True
        
        self._use_memory: bool = False

        if self.memory is not None:
            self._use_memory = True

        if self.policy is not None:
            self._apply_policy()


    def run_sync(self, query: str):
        '''
        ### Definition
        - Method used to run user query by interacting with the LLM and making tool-calls whenever necessary
        - This method mainly focuses on driving the event loop of an agent.
          - By sending the current conversation state along with the available tools for this agent, it either returns
          a final answer or makes a tool call.
          - Event Loop continues until an response type is produced without an tool call or Maximum iterations reached.

        ### Arguments
        query: `str` =>  The user input that should be processed by the agent.

        ### Returns
        - Concluding response generated by the agent before/after an reasoning.

        ### Raises
        - **MaxIterationsError** => raises when the maximum number of iterations is reached without providing an concluding response
        '''
        try:
            asyncio.get_running_loop()
        except RuntimeError:
            return asyncio.run(self.run(query=query))
        else:
            raise RuntimeError(
                "Cannot call run_sync() inside a running event loop. "
                "Use 'await agent.run()' instead."
            )

    def _apply_policy(self) -> None:
        if self.policy is not None:
            if self.policy.use_memory is not None:
                self._use_memory = self.policy.use_memory
            
            if self.policy.use_conversational_history is not None:
                self._use_conversational_history = self.policy.use_conversational_history

            if self.policy.use_tools is not None and not self.policy.use_tools:
                self.tools = []
                self._tool_registry = {}
                self.tool_executor = None
        

    async def run(self, query: str) -> str:
        '''
        ### Definition
        - Asynchronous method used to run user query by interacting with the LLM and making tool-calls whenever necessary
        - This method mainly focuses on driving the event loop of an agent.
          - By sending the current conversation state along with the available tools for this agent, it either returns
          a final answer or makes a tool call.
          - Event Loop continues until an response type is produced without an tool call or Maximum iterations reached.

        ### Arguments
        query: `str` =>  The user input that should be processed by the agent.

        ### Returns
        - Concluding response generated by the agent before/after an reasoning.

        ### Raises
        - **MaxIterationsError** => raises when the maximum number of iterations is reached without providing an concluding response
        '''
        
        formatted_tools = self.formatter.format_many(self.tools) if self.tools else []

        if self._use_conversational_history:
            conversation = self.conversation
        else:
            conversation = Conversation(self.system_prompt)

        conversation.add_user(content=query)

        '''Memory Retrieval'''
        if self._use_memory and self.memory is not None:
            memory_retrieval = await self.memory.retrieve(
                query=query,
                k=5
            )

            '''Only retrieve memory if persistent memory module exists'''
            for item in memory_retrieval:
                conversation.add_system(
                    content=f"[Memory] {item}"
                )

        for _ in range(self.max_iter):
            response = await self.adapter.complete(
            conversation.get_messages(),
            formatted_tools
        )
                
            if response.response_type == "text":
                if response.content is not None:

                    conversation.add_assistant(content=response.content)

                    '''Store to persistent memory if we have an persistent memory defined'''
                    if self._use_memory and self.memory is not None:
                        await self.memory.push(
                            text=response.content,
                            role="assistant",
                            metadata = {"type": "response"}
                        )

                    return response.content
                
            elif response.response_type == "tool_call":
                if not self.tool_executor:
                    raise RuntimeError("Tool call was requested even though Agent has no tools defined.")
                
                if response.raw and response.raw.get("message"):
                    conversation.add_assistant(content=response.raw.get("message"))
                tool_results = await self.tool_executor.execute(response.tool_calls)

                conversation.add_tool_results(tool_results)

                if self._use_memory and self.memory is not None:
                        await self.memory.push(
                            text=str(tool_results),
                            role="assistant",
                            metadata = {"type": "tool_result"}
                        )
                
                continue

        raise MaxIterationsError(self.max_iter)