from ..adapters.adapter import AgentAdapter
from .events.event_dispatcher import EventDispatcher
from .events.agent_events import AgentEvents
from ..schemas import User, AgentInfo

import asyncio
import logging

from uuid import UUID
from typing import Optional
from abc import ABC, abstractmethod

logger = logging.getLogger(__name__)

class AgentBase(ABC):
    """
    ### Definition
    - Base class for all Agents that is responsible for handling prompts and
    flow of interaction with a `LLM` (Large Language Model) Adapter.

    ### Arguments
    - **adapter**: `AgentAdapter`
       - Interface for communicating with the underlying LLM.
    - **system_prompt**: `str`
       - Combination of agent role and prompt that defines the agent's behavior
    """
    def __init__(
            self,
            adapter: AgentAdapter,
            name: Optional[str],
            key: Optional[str],
            role: Optional[str] = None,
            prompt: Optional[str] = None,
    ) -> None:
        self.me: AgentInfo = AgentInfo(
            id=UUID("6d515d56-0b48-4c51-b31e-bd98df8554da"),
            name = name or "Lily",
            key = key or "assistant",
            role = role or "You are Lily, a helpful agent developed by Shree",
            prompt = prompt or "Respond accurately and effectively to user requests."
        )
        self.adapter: AgentAdapter = adapter
        self._agent_event_handler = EventDispatcher()

        self._agent_event_handler.preload_events({
            AgentEvents.ON_AGENT_TEXT_RESPONSE
        })

        logger.info(
            "Initialized Agent",
            extra = {
                "agent_name": self.me.name,
                "key": self.me.key,
                "role": self.me.role
            }
        )


    def run_sync(self, query: str, user_id: Optional[str]=None, **kwargs):
        """
        ### Definition
        - Synchronous method used to run user query by interacting with the LLM
        ### Arguments
        query: `str` =>  The user input that should be processed by the agent.

        ### Returns
        - Concluding response generated by the agent before/after an reasoning.

        ### Raises
        - RuntimeError
          - If the method is invoked inside an event loop.
        """
        try:
            asyncio.get_running_loop()
        except RuntimeError:
            return asyncio.run(self.run(query=query, user_id=user_id))
        else:
            raise RuntimeError(
                "Cannot call run_sync() inside a running event loop. "
                "Use 'await agent.run()' instead."
            )


    @abstractmethod
    async def run(self, query: str, user: Optional[User]=None, **kwargs) -> str:
        """
        ### Definition
        - Asynchronous abstract method used to run user query by interacting with the LLM

        ### Arguments
        query: `str` =>  The user input that should be processed by the agent.

        ### Returns
        - Concluding response generated by the agent before/after an reasoning.

        """
        ...

    def event(self, func=None):
        def decorator(fn):
            event_name = fn.__name__
            self._agent_event_handler.register(event_name, fn)
            return fn

        if func is None:
            return decorator
        return decorator(func) 