# agent.py

from ..adapters.core.adapter import AgentAdapter
from ..tools.base.tool_base import Tool
from ..formatters.base_formatter import BaseFormatter
from ..formatters.formatter import Formatter
from ..adapters.core.adapter_classes import Message
from .agent_exceptions import MaxIterationsError
from .tool_executor import ToolExecutor
from ..memory.conversations import Conversation
from typing import List, Optional, Any


class LilyAgent:
    """
    ### Definition
    - Base class for all Agents that is responsible for handling prompts and
    flow of interaction with a `LLM` (Large Language Model) Adapter.
    - It maintains conversational state, manages available **Tools** and **__Formatters__**,
    formats input and output responses for the model.

    ### Class Attributes
    - **tools**: `List[Tool]` => The list of tools available for an agent to perform actions/tool calls
    - **system_prompt**: `str` => Combination of agent role and prompt that defines the agent's behavior
    - **formatter**: `Formatter` => Responsible for formatting tool schema depending on the LLM.
    - **adapter**: `AgentAdapter` => Interface for communicating with the underlying LLM.
    - **messages**: `List[Message]` => Conversational history
    """

    def __init__(self, adapter: AgentAdapter, tools: Optional[List[Tool]]=None, formatter: Optional[Formatter] = None, role: Optional[str] = None ,prompt: Optional[str] = None, max_iter: int = 3) -> None:
        self.tools: List[Tool] = tools or []

        '''Default fallback role'''
        self.role = role if role is not None else "You are Lily, a helpful agent developed by Shree"
        '''Default fallback prompt'''
        self.prompt = prompt if prompt is not None else "Answer to user prompts and use tools whenever necessary."
        self.system_prompt: str = f"{self.role}\n\n{self.prompt}"
        self.max_iter: int = max_iter
        
        self.formatter = formatter if formatter is not None else BaseFormatter()
        self.adapter: AgentAdapter = adapter

        self.tool_executor: Optional[ToolExecutor] = ToolExecutor(tools=self.tools) if self.tools else None

        self.conversation: Conversation =  Conversation(self.system_prompt)


    def run_sync(self, query: str) -> str:
        '''
        ### Definition
        - Method used to run user query by interacting with the LLM and making tool-calls whenever necessary
        - This method mainly focuses on driving the event loop of an agent.
          - By sending the current conversation state along with the available tools for this agent, it either returns
          a final answer or makes a tool call.
          - Event Loop continues until an response type is produced without an tool call or Maximum iterations reached.

        ### Arguments
        query: `str` =>  The user input that should be processed by the agent.

        ### Returns
        - Concluding response generated by the agent before/after an reasoning.

        ### Raises
        - **MaxIterationsError** => raises when the maximum number of iterations is reached without providing an concluding response
        '''
        
        self.conversation.add_user(content=query)
        formatted_tools = self.formatter.format_many(self.tools) if self.tools else []
 
        for _ in range(self.max_iter):
            response = self.adapter.complete_sync(self.conversation.get_messages(), formatted_tools)
            if response.response_type == "text":
                if response.content is not None:
                    self.conversation.add_assistant(content=response.content)
                    return response.content
            elif response.response_type == "tool_call":
                if not self.tool_executor:
                    raise RuntimeError("Tool call was requested even though Agent has no tools defined.")
                if response.raw and response.raw.get("message"):
                    self.conversation.add_assistant(content=response.raw.get("message"))
                tool_results = self.tool_executor.execute_sync(response.tool_calls)
                self.conversation.add_tool_results(tool_results)
                continue

            
        raise MaxIterationsError(self.max_iter)

    async def run(self, query: str) -> str:
        '''
        ### Definition
        - Asynchronous method used to run user query by interacting with the LLM and making tool-calls whenever necessary
        - This method mainly focuses on driving the event loop of an agent.
          - By sending the current conversation state along with the available tools for this agent, it either returns
          a final answer or makes a tool call.
          - Event Loop continues until an response type is produced without an tool call or Maximum iterations reached.

        ### Arguments
        query: `str` =>  The user input that should be processed by the agent.

        ### Returns
        - Concluding response generated by the agent before/after an reasoning.

        ### Raises
        - **MaxIterationsError** => raises when the maximum number of iterations is reached without providing an concluding response
        '''
        self.conversation.add_user(content=query)
        formatted_tools = self.formatter.format_many(self.tools) if self.tools else []

        for _ in range(self.max_iter):
            response = await self.adapter.complete(
            self.conversation.get_messages(),
            formatted_tools
        )
            
            if response.response_type == "text":
                if response.content is not None:
                    self.conversation.add_assistant(content=response.content)
                    return response.content
            elif response.response_type == "tool_call":
                if not self.tool_executor:
                    raise RuntimeError("Tool call was requested even though Agent has no tools defined.")
                if response.raw and response.raw.get("message"):
                    self.conversation.add_assistant(content=response.raw.get("message"))
                tool_results = await self.tool_executor.execute(response.tool_calls)
                self.conversation.add_tool_results(tool_results)
                continue

        raise MaxIterationsError(self.max_iter)