from typing import List, Dict, Any, Optional
from lily_agent.adapters.core import AgentAdapter
from lily_agent.adapters.core.adapter_classes import Message, LLMResponse, ToolCall
from lily_agent.adapters.core.adapter_exceptions import AdapterError

import json

class GroqAdapter(AgentAdapter):
    def __init__(
            self, model: str, 
            base_endpoint: str | None = None,
            path: str | None = None, 
            api_key: str | None = None,  
            timeout: float = 300.0,
            **kwargs
        ) -> None:

        base_endpoint = base_endpoint or "https://api.groq.com/openai" # Base Endpoint.
        path = path or "/v1/chat/completions"  # Chat completion route

        super().__init__(model, base_endpoint, path ,api_key, timeout ,**kwargs)

    def _build_request(self, messages: List[Message], tools: List[dict], think: bool) -> dict:
        '''Start by creating a list of messages''' 
        messages_list: List[dict] = []

        '''Iterate through all the messages one by one'''
        for message in messages:
            '''Get the content of the message'''
            message_content = message.content
            

            '''If message content is actually a tool call result then let's convert it to json'''
            if isinstance(message_content, (dict, list)):
                message_content = json.dumps(message_content)


            '''Let's create a new dictionary per message'''
            messages_mapped: Dict[str, Any] = {
                "content": message_content
            } 

            '''If the message contains a role which is a tool_result, then we set the map role => tool.  Else we set the default role that we got from the agent.'''
            if message.role == "tool_result":
                messages_mapped["role"] = "tool"
                if message.tool_call_id:
                    messages_mapped["tool_call_id"] = message.tool_call_id
            else:
                messages_mapped["role"] = message.role
                    
            messages_list.append(messages_mapped)

        '''Let's finalise the payload and return it.'''
        request = {
            "model": self.model,
            "messages": messages_list,
        }

        '''If we have tools on our agent, lets add an key-value Pair'''
        if tools:
            request["tools"] = tools
            request["tool_choice"] = "auto" # Expected by the api.

        '''Convert thinking to temperature.'''
        if think:
            request["temperature"] = 0.2

        return request
    
    def _parse_response(self, response: Any) -> LLMResponse:

        '''Getting the choices dictionary from the response'''
        choices = response.get("choices", [])

        '''If there is no choices returned by the api then Let's raise an exception'''
        if not choices:
            raise AdapterError("No choices returned from Groq response")

        '''Let's extract the first message and it's contents from choices'''
        message = choices[0].get("message", {})
        content = message.get("content", None)

        '''Define an empty list of tool_calls that the agent expects'''
        tool_calls: List[ToolCall] = []

        '''We will retrive the tool_calls that the LLM returned in the response'''
        raw_tool_calls = message.get("tool_calls")

        if raw_tool_calls: # If there is a tool_call requested by the LLM
            '''We iterate through the tool call to get expected parameters to build ToolCall'''
            for tool_call in raw_tool_calls:
                function: Optional[Dict] = tool_call.get("function")
                if function is None:
                    raise AdapterError("Tool call missing 'function'")

                tool_call_id: str = tool_call.get("id") # ID Generated by the LLM
                '''Getting the function name from the dictionary'''
                tool_name: Optional[str] = function.get("name") 

                if tool_name is None:
                    raise AdapterError("Tool call missing 'name'")

                '''Getting the arguments of the function extracted by the LLM'''
                arguments = function.get("arguments", "{}")
                tool_arguments = json.loads(arguments)

                '''Append the request tool_call to the dict'''
                tool_calls.append(
                    ToolCall(
                        id=tool_call_id,
                        name=tool_name,
                        input=tool_arguments
                    )
                )

            '''We return an LLMResponse with the type=tool_call and all the parameters extracted'''

            return LLMResponse(
                response_type="tool_call",
                content=content,
                tool_calls=tool_calls,
                raw=response
            )

        '''Default Fallback finish_reason = stop'''    
        return LLMResponse(
            response_type="text",
            content=content,
            tool_calls=None,
            raw=response
        )