from ..adapter import AgentAdapter
from typing import List, Any, Dict, Optional
from ..adapter_classes import LLMResponse, Message, ToolCall
from ..adapter_exceptions import AdapterError

import httpx
import json


class OllamaAdapter(AgentAdapter):
    def __init__(self, model: str, base_endpoint: str | None = "http://localhost:11434", api_key: str | None = None, **kwargs) -> None:
        super().__init__(model, base_endpoint, api_key, **kwargs)

    def complete(self, messages: List[Message], tools: List[dict]) -> LLMResponse:
        '''
        ### Definition
        - Responsible for sending messages to the model and returning a structure concluded LLM Response
        ### Execution steps
        - Builds the request (takes in messages and set of tools)
          - Internally uses `_build_request`
        - Sends it to the LLM
          - Internally uses `_call`
        - Processes the raw response
          - Internally uses `_parse_response`

        ### Raises
        - AdapterError
          - If any error was raised during the execution process.
        '''
        try:
            request: dict = self._build_request(messages=messages, tools=tools)
            response: dict = self._call(request=request)
            return self._parse_response(response=response)
        except AdapterError:
            raise
        except Exception as e:
            raise AdapterError(f"Unexpected error occured: {e}") from e

    def _build_request(self, messages: List[Message], tools: List[dict]) -> dict:
        '''
        ### Definition
        - Builds dynamic requests payload for the LLM to understand. 
        ### Parameters
        - **messages**: `List[Message]` =>  List of Message objects to be converted into the compatible format
        - **tools**: `List[dict]` => Tools to include onto the request (payload-alike)

        ### Returns
        - `dict` => a response representing the request body
        '''

        messages_list: List = []
        for message in messages:
            messages_mapped: Dict[str, Any] = {}

            '''Message content should always be a string'''
            message_content = message.content

            if isinstance(message_content, (dict, list)):
                message_content = json.dumps(message_content)

            messages_mapped["content"] = message_content

            if message.role == "tool_result":
                messages_mapped["role"] = "tool"
                if message.tool_call_id:
                    messages_mapped["tool_call_id"] = message.tool_call_id
            else:
                messages_mapped["role"] = message.role
                
            messages_list.append(messages_mapped)

        

        return  {
            "model": self.model,
            "messages": messages_list,
            "tools": tools,
            "stream": False
        }
    

    def _call(self, request: dict) -> Any:
        '''
        ### Definition
        - Sends an POST request to the OLLAMA API'S Endpoint and returns the json response
        ### Parameters
        - **request** => request payload generated by `_build_request`
        ### Returns
        - `Any`=>  Response from the api (Typically JSON)
        ### Raises
        - **ConnectError**
          - If OLLAMA is not currently running.
        - **HTTPStatusError**
          - If HTTP Status error was raised
        '''
        try:
            response: httpx.Response = httpx.post(f'{self.base_endpoint}/api/chat', json=request, timeout=300.0)
            response.raise_for_status()
            return response.json()
        except httpx.ConnectError:
            raise AdapterError(f"Could not connect to Ollama at {self.base_endpoint}. Make sure ollama is running")
        except httpx.HTTPStatusError as e:
            response_status: int = e.response.status_code

            if response_status == 404:
                raise AdapterError(f"The response returned {e.response.status_code}") from e
            elif response_status == 401:
                raise AdapterError("Unauthorized (401)") from e
            elif response_status == 403:
                raise AdapterError("Forbidden (403)") from e
            else:
                raise AdapterError(f"HTTP error {response_status}: {e.response.text}") from e

    def _parse_response(self, response: Any) -> LLMResponse:
        '''
        ### Definition
        - Parses the raw api response into a structure LLMResponse
        ### LLMResponse
        - **response_type**: `Literal`
          - Anything in "text", "tool_call", "stop"
            #### text: ``
            - Text Response
            #### tool_call: ``
            - If one or more tool calls was made
            #### stop: ``
            - Stopping the execution flow
        - **content**: `Optional[str]`
          - Content generated by the LLM
        - tool_calls: `Optional[List[ToolCall]]`
          - List of tool calls requested by the LLM
        - raw: `Any`
          - Unprocessed response from the LLM
        '''
        tool_calls: List[ToolCall] = []

        message = response.get("message")
        content = message.get("content", None)

        if message.get("tool_calls"):
            
            '''Building Tool Calls'''
            for tool_call in message.get("tool_calls", []):
                function: Optional[Dict] = tool_call.get("function")

                if function is None:
                    raise AdapterError("Tool call missing 'function'")

                tool_call_id: str = tool_call.get("id")
                
                tool_name: Optional[str] = function.get("name")

                if tool_name is None:
                    raise AdapterError("Tool call missing 'name'")

                tool_arguments: dict = function.get("arguments", {})
                tool_calls.append(ToolCall(id=tool_call_id, name=tool_name, input=tool_arguments))

            return LLMResponse(response_type="tool_call", content=content, tool_calls=tool_calls, raw=response)
        else:
            return LLMResponse(response_type="text", content=content, tool_calls=None, raw=response)