from ..core.adapter import AgentAdapter
from typing import List, Any, Dict, Optional
from ..core.adapter_classes import LLMResponse, Message, ToolCall
from ..core.adapter_exceptions import AdapterError

import httpx
import json


class OllamaAdapter(AgentAdapter):
    def __init__(
            self, 
            model: str, 
            base_endpoint: Optional[str] = "http://localhost:11434", 
            path: Optional[str] = "/api/chat",
            api_key: Optional[str] = None, 
            timeout: float=300.0,
            **kwargs
        ) -> None:
        super().__init__(model, base_endpoint, path, api_key ,timeout ,**kwargs)


    def _build_request(self, messages: List[Message], tools: List[dict], think: bool) -> dict:
        '''
        ### Definition
        - Builds dynamic requests payload for the LLM to understand. 
        ### Parameters
        - **messages**: `List[Message]` =>  List of Message objects to be converted into the compatible format
        - **tools**: `List[dict]` => Tools to include onto the request (payload-alike)

        ### Returns
        - `dict` => a response representing the request body
        '''

        messages_list: List = []
        for message in messages:
            messages_mapped: Dict[str, Any] = {}

            '''Message content should always be a string'''
            message_content = message.content

            if isinstance(message_content, (dict, list)):
                message_content = json.dumps(message_content)

            messages_mapped["content"] = message_content

            if message.role == "tool_result":
                messages_mapped["role"] = "tool"
                if message.tool_call_id:
                    messages_mapped["tool_call_id"] = message.tool_call_id
            else:
                messages_mapped["role"] = message.role
                
            messages_list.append(messages_mapped)

        

        return  {
            "model": self.model,
            "messages": messages_list,
            "tools": tools,
            "stream": False,
            "think": think
        }

    def _parse_response(self, response: Any) -> LLMResponse:
        '''
        ### Definition
        - Parses the raw api response into a structure LLMResponse
        ### LLMResponse
        - **response_type**: `Literal`
          - Anything in "text", "tool_call", "stop"
            #### text: ``
            - Text Response
            #### tool_call: ``
            - If one or more tool calls was made
            #### stop: ``
            - Stopping the execution flow
        - **content**: `Optional[str]`
          - Content generated by the LLM
        - tool_calls: `Optional[List[ToolCall]]`
          - List of tool calls requested by the LLM
        - raw: `Any`
          - Unprocessed response from the LLM
        '''
        tool_calls: List[ToolCall] = []

        message = response.get("message")
        content = message.get("content", None)

        if message.get("tool_calls"):
            
            '''Building Tool Calls'''
            for tool_call in message.get("tool_calls", []):
                function: Optional[Dict] = tool_call.get("function")

                if function is None:
                    raise AdapterError("Tool call missing 'function'")

                tool_call_id: str = tool_call.get("id")
                
                tool_name: Optional[str] = function.get("name")

                if tool_name is None:
                    raise AdapterError("Tool call missing 'name'")

                tool_arguments: dict = function.get("arguments", {})
                tool_calls.append(ToolCall(id=tool_call_id, name=tool_name, input=tool_arguments))

            return LLMResponse(response_type="tool_call", content=content, tool_calls=tool_calls, raw=response)
        else:
            return LLMResponse(response_type="text", content=content, tool_calls=None, raw=response)
        