from ...adapters.core.adapter import AgentAdapter
from ...tools.base.tool_base import Tool
from ...formatters.base_formatter import BaseFormatter
from ...formatters.formatter import Formatter
from ..errors.agent_exceptions import MaxIterationsError
from ..tool_executor import ToolExecutor
from ...memory.conversations import Conversation
from ...memory.core.memory import MemoryBase
from ...policy.agent_policy import AgentPolicy
from ..core.agent_base import AgentBase
from ..events.agent_events import AgentEvents
from ...registry.agent_registry import AgentRegistry, AgentInfo
from ...vectorstore.core.vector_store import VectorRetrieval
from ...registry.integrations.json_registry import JSONRegistry


from ..events.event_classes import (
    TextResponse,
    MemoryStore
)

from typing import Optional, List
import asyncio


class LilyAgent(AgentBase):
    """
    ### Definition
    - Base class for all Agents that is responsible for handling prompts and
    flow of interaction with a `LLM` (Large Language Model) Adapter.
    - It maintains conversational state, manages available **Tools** and **__Formatters__**,
    formats input and output responses for the model.

    ### Class Attributes
    - **tools**: `List[Tool]` => The list of tools available for an agent to perform actions/tool calls
    - **system_prompt**: `str` => Combination of agent role and prompt that defines the agent's behavior
    - **formatter**: `Formatter` => Responsible for formatting tool schema depending on the LLM.
    - **adapter**: `AgentAdapter` => Interface for communicating with the underlying LLM.
    - **messages**: `List[Message]` => Conversational history
    """

    def __init__(
            self, 
            adapter: AgentAdapter, 
            memory: Optional[MemoryBase] = None,
            tools: Optional[List[Tool]]=None, 
            formatter: Optional[Formatter] = None, 
            role: Optional[str] = None ,
            prompt: Optional[str] = None, 
            name: Optional[str] = None,
            key: Optional[str] = None,
            max_iter: int = 3,
            policy: Optional[AgentPolicy] = None,
            registry: Optional[AgentRegistry] = None
    ) -> None:
        
        super().__init__(adapter=adapter, role=role, prompt=prompt, name=name, key=key)

        """ Preloading all events """
        self._agent_event_handler.preload_events({
            AgentEvents.ON_TOOL_CALL_REQUESTED,
            AgentEvents.ON_TOOL_EXECUTION_STARTED,
            AgentEvents.ON_TOOL_EXECUTION_COMPLETED,
            AgentEvents.ON_TOOL_EXECUTION_FAILED,

            AgentEvents.ON_MEMORY_RETRIEVED,
            AgentEvents.ON_MEMORY_STORED
        })
        
        self.tools: List[Tool] = tools or []
        self.max_iter: int = max_iter
        self.formatter = formatter if formatter is not None else BaseFormatter()
        self.tool_executor: Optional[ToolExecutor] = ToolExecutor(tools=self.tools, event_handler=self._agent_event_handler) if self.tools else None
        self.conversation: Conversation =  Conversation(self.system_prompt)
        self.memory: Optional[MemoryBase] = memory
        self.policy: Optional[AgentPolicy] = policy
        self.registry: AgentRegistry = registry or JSONRegistry()

        
        self._use_conversational_history: bool = True
        self._use_memory: bool = False
        self._store_memory: bool = False

        if self.memory is not None:
            self._use_memory = True

        if self.policy is not None:
            self._apply_policy()

        """ Only create a registry if self._store memory is true """
        self.agent_id = self.registry.register(
            agent_key=self.key,
            name=self.name,
            role=self.role,
            prompt=self.prompt
        )

    def run_sync(self, query: str, user_id: Optional[str]=None):
        '''
        ### Definition
        - Method used to run user query by interacting with the LLM and making tool-calls whenever necessary
        - This method mainly focuses on driving the event loop of an agent.
          - By sending the current conversation state along with the available tools for this agent, it either returns
          a final answer or makes a tool call.
          - Event Loop continues until an response type is produced without an tool call or Maximum iterations reached.

        ### Arguments
        query: `str` =>  The user input that should be processed by the agent.

        ### Returns
        - Concluding response generated by the agent before/after an reasoning.

        ### Raises
        - **MaxIterationsError** => raises when the maximum number of iterations is reached without providing an concluding response
        '''
        try:
            asyncio.get_running_loop()
        except RuntimeError:
            return asyncio.run(self.run(query=query, user_id=user_id))
        else:
            raise RuntimeError(
                "Cannot call run_sync() inside a running event loop. "
                "Use 'await agent.run()' instead."
            )

    def _apply_policy(self) -> None:
        if self.policy is not None:
            if self.policy.use_memory is not None:
                self._use_memory = self.policy.use_memory
            
            if self.policy.use_conversational_history is not None:
                self._use_conversational_history = self.policy.use_conversational_history

            if self.policy.use_tools is not None and not self.policy.use_tools:
                self.tools = []
                self._tool_registry = {}
                self.tool_executor = None

            if self.policy.store_memory is not None:
                self._store_memory = self.policy.store_memory

    def event(self, func=None):
        def decorator(fn):
            event_name = fn.__name__
            self._agent_event_handler.register(event_name, fn)
            return fn

        if func is None:
            return decorator
        return decorator(func)

    def register_tool(self, tools: Tool | List[Tool]):
        """ Adding tools here """
        if isinstance(tools, Tool):
                self.tools.append(tools)
            
        else:
            self.tools.extend(tools)


        if self.tool_executor is not None:
            self.tool_executor.register(tool=tools)
        else:
            self.tool_executor = ToolExecutor(tools=self.tools, event_handler=self._agent_event_handler)
            

    async def run(self, query: str, user_id: Optional[str]=None) -> str:
        '''
        ### Definition
        - Asynchronous method used to run user query by interacting with the LLM and making tool-calls whenever necessary
        - This method mainly focuses on driving the event loop of an agent.
          - By sending the current conversation state along with the available tools for this agent, it either returns
          a final answer or makes a tool call.
          - Event Loop continues until an response type is produced without an tool call or Maximum iterations reached.

        ### Arguments
        query: `str` =>  The user input that should be processed by the agent.

        ### Returns
        - Concluding response generated by the agent before/after an reasoning.

        ### Raises
        - **MaxIterationsError** => raises when the maximum number of iterations is reached without providing an concluding response
        '''
        
        formatted_tools = self.formatter.format_many(self.tools) if self.tools else []
        print(formatted_tools)

        if self._use_conversational_history:
            conversation = self.conversation
        else:
            conversation = Conversation(self.system_prompt)

        conversation.add_user(content=query)


        """ Memory Retrieval """
        if self._use_memory and self.memory is not None:
            """ Create Filters """
            filters = {"agent_id": self.agent_id}

            if user_id is not None:
                filters["user_id"] = user_id


            memory_retrieval: List[VectorRetrieval] = await self.memory.retrieve(
                query=query,
                filters=filters,
                k=5
            )

            if len(memory_retrieval) > 0:
                '''Only retrieve memory if persistent memory module exists'''
                for retrieval in memory_retrieval:
                    conversation.add_system(
                        content=f"[Memory] {retrieval.text}"
                    )

                await self._agent_event_handler.invoke(AgentEvents.ON_MEMORY_RETRIEVED, memory_retrieval)

        for _ in range(self.max_iter):
            response = await self.adapter.complete(
            conversation.get_messages(),
            formatted_tools
        )
                
            if response.response_type == "text":
                if response.content is not None:

                    conversation.add_assistant(content=response.content)

                    """ Store to persistent memory if we have an persistent memory defined """
                    if self._store_memory and self.memory is not None:
                        memory_store: MemoryStore = await self.memory.push(
                            text=query,
                            agent_id=self.agent_id,
                            user_id=user_id
                        )
                        await self._agent_event_handler.invoke(AgentEvents.ON_MEMORY_STORED, memory_store)

                    await self._agent_event_handler.invoke(AgentEvents.ON_AGENT_TEXT_RESPONSE, TextResponse(content=response.content))

                    return response.content
                
            elif response.response_type == "tool_call":
                if not self.tool_executor:
                    raise RuntimeError("Tool call was requested even though Agent has no tools defined.")
                
                await self._agent_event_handler.invoke(AgentEvents.ON_TOOL_CALL_REQUESTED)
                                
                if response.raw and response.raw.get("message"):
                    conversation.add_assistant(content=response.raw.get("message"))

                tool_results = await self.tool_executor.execute(response.tool_calls)

                conversation.add_tool_results(tool_results)

                if self._store_memory and self.memory is not None:
                        memory_store: MemoryStore = await self.memory.push(
                            text=str(tool_results),
                            agent_id=self.agent_id,
                            user_id=user_id
                        )

                        await self._agent_event_handler.invoke(AgentEvents.ON_MEMORY_STORED, memory_store)

                
                continue

        raise MaxIterationsError(self.max_iter)