from ...adapters.core.adapter import AgentAdapter
from typing import Optional
from abc import ABC, abstractmethod
from ..events.event_dispatcher import EventDispatcher
from ..events.agent_events import AgentEvents

import asyncio

class AgentBase(ABC):
    """
    ### Definition
    - Base class for all Agents that is responsible for handling prompts and
    flow of interaction with a `LLM` (Large Language Model) Adapter.

    ### Arguments
    - **adapter**: `AgentAdapter`
       - Interface for communicating with the underlying LLM.
    - **system_prompt**: `str`
       - Combination of agent role and prompt that defines the agent's behavior
    """
    def __init__(
            self,
            adapter: AgentAdapter,
            role: Optional[str] = None ,
            prompt: Optional[str] = None, 
    ) -> None:
        
        """ Default fallback role """
        self.role = role if role is not None else "You are Lily, a helpful agent developed by Shree"

        """ Default fallback prompt """
        self.prompt = prompt if prompt is not None else "Respond accurately and effectively to user requests."
        self.system_prompt: str = f"{self.role}\n\n{self.prompt}"

        """ Adapter Assignment """
        self.adapter: AgentAdapter = adapter


        """ Event Handlers """
        self._agent_event_handler = EventDispatcher()

        """ Preload an event """
        self._agent_event_handler.preload_events({
            AgentEvents.ON_AGENT_TEXT_RESPONSE
        })



    def run_sync(self, query: str):
        """
        ### Definition
        - Synchronous method used to run user query by interacting with the LLM
        ### Arguments
        query: `str` =>  The user input that should be processed by the agent.

        ### Returns
        - Concluding response generated by the agent before/after an reasoning.

        ### Raises
        - RuntimeError
          - If the method is invoked inside an event loop.
        """
        try:
            asyncio.get_running_loop()
        except RuntimeError:
            return asyncio.run(self.run(query=query))
        else:
            raise RuntimeError(
                "Cannot call run_sync() inside a running event loop. "
                "Use 'await agent.run()' instead."
            )


    @abstractmethod
    async def run(self, query: str) -> str:
        """
        ### Definition
        - Asynchronous abstract method used to run user query by interacting with the LLM

        ### Arguments
        query: `str` =>  The user input that should be processed by the agent.

        ### Returns
        - Concluding response generated by the agent before/after an reasoning.

        """
        ...

    def event(self, func=None):
        def decorator(fn):
            event_name = fn.__name__
            self._agent_event_handler.register(event_name, fn)
            return fn

        if func is None:
            return decorator
        return decorator(func)