from lily_agent.formatters import Formatter
from lily_agent.tools import Tool
from typing import Dict, Any

class AnthropicFormatter(Formatter):
    def format(self, tool: Tool) -> Dict[str, Any]:
        """ This is the paramter schema generated by pydantic.  It's common for all. """
        schema = tool.input_schema.copy() 

        return {
            "name" : tool.name, # Accessing the tool name
            "description": tool.description, # Accessing the tool's description
            "input_schema": schema # The schema generated by pydantic
        }