# adapter.py

from abc import ABC, abstractmethod
from typing import Optional
from typing import List, Any
from .adapter_exceptions import AdapterError
from .adapter_classes import LLMResponse, Message

class AgentAdapter(ABC):
    '''
    ### Definition
    -  Abstract base class that defines a standard way of interacting with different language model
    providers such as OLLAMA, Open AI Etc...
    - Ensures all adapter flow follows the same structure and behavior making the system modular, extensible and consistent

    ### Purpose
    - Uses an adapter design pattern for all LLM Integrations
    - Enforces strict implementations of core methods
    - Allows to swap different providers without changing the core system functionality

    ### Parameters
    - **model**: `str`
      - Name of the model to be used (example qwen3:8b)
    - **base_endpoint**: `Optional[str]`
      - API url for communicating with the LLM
    - **api_key**: `Optional[str]`
      - Auth key for communicating with the api
    - ****kwargs****
      - Additional configurations
    '''
    def __init__(self, model: str, base_endpoint: Optional[str]=None, api_key: Optional[str]=None, **kwargs) -> None:
        self.model = model
        self.base_endpoint = base_endpoint
        self.api_key = api_key
        self.config = kwargs

    def complete_sync(self, messages: List[Message], tools: List[dict], think: bool=False) -> LLMResponse:
        '''
        ### Definition
        - Main entry point for generating an response from the LLM.
        - This pattern is followed for most of the AI LLM.  so it's already implemented.
        ### Responsible for
        - Building the request (takes in messages and set of tools)
          - Internally uses `_build_request`
        - Sending it to the LLM
          - Internally uses `_call`
        - Processing the raw response
          - Internally uses `_parse_response`
        ### Returns
        `LLMResponse`
          - Structured LLM response,
        '''
        try:
            request = self._build_request(messages, tools, think)
            response = self._call_sync(request)
            return self._parse_response(response)

        except AdapterError:
            raise

        except Exception as e:
            raise AdapterError(f"Unexpected error occurred: {e}") from e
        
    async def complete(self, messages: List[Message], tools: List[dict], think: bool = False) -> LLMResponse:
      '''
        ### Definition
        - Main asynchronous entry point for generating an response from the LLM.
        - This pattern is followed for most of the AI LLM.  so it's already implemented.
        ### Responsible for
        - Building the request (takes in messages and set of tools)
          - Internally uses `_build_request`
        - Sending it to the LLM
          - Internally uses `_call`
        - Processing the raw response
          - Internally uses `_parse_response`
        ### Returns
        `LLMResponse`
          - Structured LLM response,
        '''
      try:
          request = self._build_request(messages, tools, think)
          response = await self._call(request)
          return self._parse_response(response)

      except AdapterError:
          raise

      except Exception as e:
          raise AdapterError(f"Unexpected error occurred: {e}") from e

    @abstractmethod
    def _build_request(self, messages: List[Message], tools: List[dict], think: bool) -> dict:
        '''
        ### Definition
        - Builds dynamic requests payload for the LLM to understand. 
        ### Parameters
        - **messages**: `List[Message]` =>  List of Message objects to be converted into the compatible format
        - **tools**: `List[dict]` => Tools to include onto the request (payload-alike)

        ### Returns
        - `dict` => a response representing the request body
        '''
        raise NotImplementedError

    @abstractmethod
    def _call_sync(self, request: dict) -> Any:
        '''
        ### Definition
        - Method used to send an POST request to the API's Endpoint and returns the json response
        ### Parameters
        - **request** => request payload generated by `_build_request`
        ### Returns
        - `Any`=>  Response from the api (Typically JSON)
        ### Raises
        - Handling all sorts of errors raised during the exception.
        '''
        raise NotImplementedError
    
    @abstractmethod
    async def _call(self, request: dict) -> Any:
        '''
        ### Definition
        - Method used to send an asynchronous POST request to the API's Endpoint and returns the json response
        ### Parameters
        - **request** => request payload generated by `_build_request`
        ### Returns
        - `Any`=>  Response from the api (Typically JSON)
        ### Raises
        - Handling all sorts of errors raised during the exception.
        '''
        raise NotImplementedError

    @abstractmethod
    def _parse_response(self, response: Any) -> LLMResponse:
        '''
        ### Definition
        - Parses the raw api response into a structure LLMResponse
        ### LLMResponse
        - **response_type**: `Literal`
          - Anything in "text", "tool_call", "stop"
            #### text: ``
            - Text Response
            #### tool_call: ``
            - If one or more tool calls was made
            #### stop: ``
            - Stopping the execution flow
        - **content**: `Optional[str]`
          - Content generated by the LLM
        - tool_calls: `Optional[List[ToolCall]]`
          - List of tool calls requested by the LLM
        - raw: `Any`
          - Unprocessed response from the LLM
        '''
        raise NotImplementedError