import asyncio
from abc import ABC, abstractmethod
from typing import Any, List, Optional

import httpx

from ..exceptions.adapter import (
    AdapterError,
    RateLimitError,
    RetryableAdapterError,
    TransientAdapterError,
)
from ..schemas import LLMResponse, Message
from ..utils import parse_retry_after
from .retry import RetryPolicy

class AgentAdapter(ABC):
    """
    ### Definition
    -  Abstract base class that defines a standard way of interacting with different language model
    providers such as OLLAMA, Open AI Etc...
    - Ensures all adapter flow follows the same structure and behavior making the system modular, extensible and consistent

    ### Purpose
    - Uses an adapter design pattern for all LLM Integrations
    - Enforces strict implementations of core methods
    - Allows to swap different providers without changing the core system functionality

    ### Parameters
    - **model**: `str`
      - Name of the model to be used (example qwen3:8b)
    - **base_endpoint**: `Optional[str]`
      - API url for communicating with the LLM
    - **api_key**: `Optional[str]`
      - Auth key for communicating with the api
    - ****kwargs****
      - Additional configurations
    """
    def __init__(
            self, 
            model: str, 
            provider: Optional[str] = None,
            base_endpoint: Optional[str]=None, 
            path: Optional[str]=None,
            api_key: Optional[str]=None,
            timeout: float = 300.0,
            think: bool = False,
            **kwargs
      ) -> None:
        
        self.model = model
        self.provider = provider
        self.base_endpoint = base_endpoint or ""
        self.path = path or ""
        self.api_key = api_key
        self.config = kwargs
        self.think = think
        self.timeout = timeout
        self.retry_policy = RetryPolicy()
        self._headers: dict = {"Content-Type": "application/json"}

        if self.api_key:
            self._headers["Authorization"] =  f"Bearer {self.api_key}"

        self._network_client = httpx.AsyncClient(timeout=timeout)


    def complete_sync(self, messages: List[Message], tools: List[dict]) -> LLMResponse:
        """
        ### Definition
        - Main entry point for generating an response from the LLM.
        - This pattern is followed for most of the AI LLM.  so it's already implemented.
        ### Responsible for
        - Building the request (takes in messages and set of tools)
          - Internally uses `_build_request`
        - Sending it to the LLM
          - Internally uses `_call`
        - Processing the raw response
          - Internally uses `_parse_response`
        ### Returns
        `LLMResponse`
          - Structured LLM response,
        """
        try:
            request = self._build_request(messages, tools)
            response = self._call_sync(request)
            return self._parse_response(response)

        except AdapterError:
            raise

        except Exception as e:
            raise AdapterError(f"Unexpected error occurred: {e}") from e
        
    async def complete(self, messages: List[Message], tools: List[dict]) -> LLMResponse:
      """
        ### Definition
        - Main asynchronous entry point for generating an response from the LLM.
        - This pattern is followed for most of the AI LLM.  so it's already implemented.
        ### Responsible for
        - Building the request (takes in messages and set of tools)
          - Internally uses `_build_request`
        - Sending it to the LLM
          - Internally uses `_call`
        - Processing the raw response
          - Internally uses `_parse_response`
        ### Returns
        `LLMResponse`
          - Structured LLM response,
      """
      try:
          request = self._build_request(messages, tools)
          response = await self._call(request)
          return self._parse_response(response)

      except AdapterError:
          raise

      except Exception as e:
          raise AdapterError(f"Unexpected error occurred: {e}") from e

    @abstractmethod
    def _build_request(self, messages: List[Message], tools: List[dict]) -> dict:
        """
        ### Definition
        - Builds dynamic requests payload for the LLM to understand. 
        ### Parameters
        - **messages**: `List[Message]` =>  List of Message objects to be converted into the compatible format
        - **tools**: `List[dict]` => Tools to include onto the request (payload-alike)

        ### Returns
        - `dict` => a response representing the request body
        """
        raise NotImplementedError

    def _call_sync(self, request: dict) -> Any:
        """
        ### Definition
        - Method used to send an POST request to the API's Endpoint and returns the json response
        ### Parameters
        - **request** => request payload generated by `_build_request`
        ### Returns
        - `Any`=>  Response from the api (Typically JSON)
        ### Raises
        - Handling all sorts of errors raised during the exception.
        '''
        try:
            asyncio.get_running_loop()
        except RuntimeError:
            return asyncio.run(self._call(request))
        else:
            raise RuntimeError("Cannot call synchronous method inside an running loop.  Consider using `_call` instead")
        """

    async def _call(self, request: dict) -> Any:

      for attempt in range(1, self.retry_policy.max_attempts + 1):
          try:
              response = await self._network_client.post(
                  self.endpoint, json=request, headers=self._headers
              )
              response.raise_for_status()
              return response.json()

          except httpx.HTTPError as e:
              if isinstance(e, httpx.HTTPStatusError):
                  status = e.response.status_code
                  if status == 429:
                      error = self._handle_rate_limit(e.response)
                  elif status >= 500:
                      error = TransientAdapterError(
                          f"HTTP {status}: {e.response.text}",
                          provider=self.provider, status_code=status,
                          retry_after=parse_retry_after(e.response.headers.get("retry-after")),
                      )
                  elif status in (401, 403, 404):
                      raise AdapterError(f"{status} from {self.base_endpoint}: {e.response.text}") from e
                  else:
                      raise AdapterError(f"HTTP error {status}: {e.response.text}") from e
              elif isinstance(e, httpx.TimeoutException):
                  error = TransientAdapterError("Request timed out", provider=self.provider)
              else:
                  error = TransientAdapterError(f"Network failure: {e}", provider=self.provider)

              if not isinstance(error, RetryableAdapterError):
                  raise error from e

              error.__cause__ = e  

          if attempt == self.retry_policy.max_attempts:
              raise error

          delay = self.retry_policy.delay_for(attempt, error.retry_after)
          if delay is None: 
              raise error
          await asyncio.sleep(delay)

      raise RuntimeError("Unreachable")

    async def _call_with_retry(self, request: dict) -> Any:
      policy = self.retry_policy
      for attempt in range(1, policy.max_attempts + 1):
          try:
              return await self._call(request)
          except RetryableAdapterError as e:
              delay = policy.delay_for(attempt, e.retry_after)
              if attempt == policy.max_attempts or delay is None:
                  raise
              await asyncio.sleep(delay)

    @abstractmethod
    def _parse_response(self, response: Any) -> LLMResponse:
        """
        ### Definition
        - Parses the raw api response into a structure LLMResponse
        ### LLMResponse
        - **response_type**: `Literal`
          - Anything in "text", "tool_call", "stop"
            #### text: ``
            - Text Response
            #### tool_call: ``
            - If one or more tool calls was made
            #### stop: ``
            - Stopping the execution flow
        - **content**: `Optional[str]`
          - Content generated by the LLM
        - tool_calls: `Optional[List[ToolCall]]`
          - List of tool calls requested by the LLM
        - raw: `Any`
          - Unprocessed response from the LLM
        """
        raise NotImplementedError


    def _handle_rate_limit(self, response: httpx.Response) -> AdapterError:
      message = f"HTTP 429: {response.text}"
      try:
          err = response.json().get("error", {})
          message = err.get("message", message)
      except (ValueError, AttributeError):
          pass

      return RateLimitError(
          message, 
          provider=self.provider, 
          status_code=429,
          retry_after=parse_retry_after(response.headers.get("retry-after"))
      )

    async def close(self):
        await self._network_client.aclose()
    
    @property
    def endpoint(self):
        return f"{self.base_endpoint.rstrip('/')}/{self.path.lstrip('/')}"